from __future__ import annotations

import json
import re
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from transformers import AutoTokenizer


# ============================================================
# Configuration
# ============================================================

DATA_DIR = Path(
    r"E:\Project RAG-SN-IN\data\processed\text\drr-2025"
)

INPUT_FILE = DATA_DIR / "_full_document.md"

OUTPUT_FILE = DATA_DIR / "chunks.jsonl"

MODEL_NAME = "google/embeddinggemma-300m"
MAX_TOKENS = 1024


# ============================================================
# Tokenizer
# ============================================================

tokenizer = AutoTokenizer.from_pretrained(
    MODEL_NAME,
    trust_remote_code=True
)


def count_tokens(text: str) -> int:
    return len(
        tokenizer.encode(
            text,
            add_special_tokens=False
        )
    )


# ============================================================
# Regular expressions
# ============================================================

# Examples:
# CHAPITRE 1
# CHAPITRE 1 — Dispositions générales
# # CHAPITRE 1 : Généralités
CHAPTER_PATTERN = re.compile(
    r"^\s*(?:#{1,6}\s*)?"
    r"CHAPITRE\s+"
    r"([0-9]+(?:\.[0-9]+)*)"
    r"(?:\s*[-–—:.)]\s*(.*))?"
    r"\s*$",
    re.IGNORECASE
)

# Markdown headings generated by Docling
MARKDOWN_HEADING_PATTERN = re.compile(
    r"^\s*(#{1,6})\s+(.+?)\s*$"
)


# ============================================================
# Data structures
# ============================================================

@dataclass
class Section:
    title: str
    level: int
    content: list[str] = field(default_factory=list)
    children: list["Section"] = field(default_factory=list)


@dataclass
class Chunk:
    text: str
    token_count: int
    header_path: list[str]
    source_file: str
    chapter_number: str | None = None


# ============================================================
# Chapter handling
# ============================================================

def parse_chapter_heading(
    line: str
) -> tuple[str | None, str | None]:
    """
    Returns the chapter number and normalized chapter title.

    Example:
        CHAPITRE 3 — Safety rules

    Returns:
        ("3", "CHAPITRE 3 — Safety rules")
    """

    match = CHAPTER_PATTERN.match(line)

    if not match:
        return None, None

    number = match.group(1)
    suffix = (match.group(2) or "").strip()

    title = f"CHAPITRE {number}"

    if suffix:
        title += f" — {suffix}"

    return number, title


def is_chapter_heading(line: str) -> bool:
    return CHAPTER_PATTERN.match(line) is not None


# ============================================================
# Markdown parser
# ============================================================

def parse_markdown(text: str) -> list[Section]:
    """
    Parses Markdown into chapters and subsections.

    Repeated chapter headings with the same number are merged.

    Example:

        CHAPITRE 1 — General rules
        text A

        CHAPITRE 1 — Exceptions
        text B

        CHAPITRE 2 — Definitions
        text C

    Becomes:

        CHAPITRE 1
            text A
            text B

        CHAPITRE 2
            text C
    """

    chapters: list[Section] = []

    current_chapter: Section | None = None
    current_chapter_number: str | None = None

    # Contains the current subsection hierarchy
    section_stack: list[Section] = []

    for raw_line in text.splitlines():
        line = raw_line.rstrip()

        # --------------------------------------------------------
        # Main chapter heading
        # --------------------------------------------------------

        chapter_number, chapter_title = parse_chapter_heading(line)

        if chapter_number is not None:
            # Same chapter repeated:
            # keep content under the existing chapter
            if (
                current_chapter is not None
                and chapter_number == current_chapter_number
            ):
                # The repeated title is not added as content.
                # It is only used as a structural signal.
                section_stack.clear()
                continue

            # New chapter number
            current_chapter = Section(
                title=f"CHAPITRE {chapter_number}",
                level=1
            )

            chapters.append(current_chapter)

            current_chapter_number = chapter_number
            section_stack.clear()

            continue

        # Ignore text before the first chapter
        if current_chapter is None:
            continue

        # --------------------------------------------------------
        # Markdown subsection heading
        # --------------------------------------------------------

        heading_match = MARKDOWN_HEADING_PATTERN.match(line)

        if heading_match:
            hashes, title = heading_match.groups()

            # A heading accidentally containing CHAPITRE should not
            # become a subsection.
            if is_chapter_heading(line):
                continue

            level = len(hashes) + 1

            section = Section(
                title=title.strip(),
                level=level
            )

            # Remove previous sections at the same or deeper level
            while (
                section_stack
                and section_stack[-1].level >= level
            ):
                section_stack.pop()

            if section_stack:
                section_stack[-1].children.append(section)
            else:
                current_chapter.children.append(section)

            section_stack.append(section)

            continue

        # --------------------------------------------------------
        # Normal content
        #
        # This includes:
        # - paragraphs
        # - bullet points
        # - numbered paragraphs
        # - tables
        # - blank lines
        # --------------------------------------------------------

        if section_stack:
            section_stack[-1].content.append(line)
        else:
            current_chapter.content.append(line)

    return chapters


# ============================================================
# Section formatting
# ============================================================

def clean_lines(lines: list[str]) -> str:
    """
    Removes excessive blank lines while preserving tables and lists.
    """

    result: list[str] = []
    previous_blank = False

    for line in lines:
        line = line.rstrip()

        if not line.strip():
            if not previous_blank:
                result.append("")
            previous_blank = True
        else:
            result.append(line)
            previous_blank = False

    return "\n".join(result).strip()


def format_direct_content(section: Section) -> str:
    """
    Formats only the title and direct content of a section.
    Children are processed separately.
    """

    parts = [section.title]

    content = clean_lines(section.content)

    if content:
        parts.append(content)

    return "\n\n".join(parts)


# ============================================================
# Chunk creation
# ============================================================

def create_chunk(
    parts: list[str],
    header_path: list[str],
    source_file: str,
    chapter_number: str | None
) -> Chunk | None:
    """
    Creates a chunk from accumulated text.
    """

    text = "\n\n".join(
        part.strip()
        for part in parts
        if part.strip()
    ).strip()

    if not text:
        return None

    return Chunk(
        text=text,
        token_count=count_tokens(text),
        header_path=header_path.copy(),
        source_file=source_file,
        chapter_number=chapter_number
    )


def split_text_by_paragraphs(text: str) -> list[str]:
    """
    Splits oversized content into paragraphs or table/list blocks.
    """

    blocks = re.split(r"\n\s*\n", text)

    return [
        block.strip()
        for block in blocks
        if block.strip()
    ]


def add_content_to_chunks(
    text: str,
    header_path: list[str],
    chunks: list[Chunk],
    source_file: str,
    chapter_number: str | None
) -> None:
    """
    Adds text to chunks.

    If the section is too large, it is split by paragraphs,
    tables, or list blocks.
    """

    if not text.strip():
        return

    token_count = count_tokens(text)

    if token_count <= MAX_TOKENS:
        chunk = create_chunk(
            parts=[text],
            header_path=header_path,
            source_file=source_file,
            chapter_number=chapter_number
        )

        if chunk:
            chunks.append(chunk)

        return

    # Oversized section: split by logical blocks
    blocks = split_text_by_paragraphs(text)

    current_blocks: list[str] = []
    current_tokens = 0

    for block in blocks:
        block_tokens = count_tokens(block)

        # A single paragraph/table is larger than the target.
        # Split it by lines instead of cutting arbitrarily.
        if block_tokens > MAX_TOKENS:
            if current_blocks:
                chunk = create_chunk(
                    parts=current_blocks,
                    header_path=header_path,
                    source_file=source_file,
                    chapter_number=chapter_number
                )

                if chunk:
                    chunks.append(chunk)

                current_blocks = []
                current_tokens = 0

            line_blocks = [
                line.strip()
                for line in block.splitlines()
                if line.strip()
            ]

            line_buffer: list[str] = []
            line_tokens = 0

            for line in line_blocks:
                line_count = count_tokens(line)

                if (
                    line_buffer
                    and line_tokens + line_count > MAX_TOKENS
                ):
                    chunk = create_chunk(
                        parts=["\n".join(line_buffer)],
                        header_path=header_path,
                        source_file=source_file,
                        chapter_number=chapter_number
                    )

                    if chunk:
                        chunks.append(chunk)

                    line_buffer = []
                    line_tokens = 0

                line_buffer.append(line)
                line_tokens += line_count

            if line_buffer:
                chunk = create_chunk(
                    parts=["\n".join(line_buffer)],
                    header_path=header_path,
                    source_file=source_file,
                    chapter_number=chapter_number
                )

                if chunk:
                    chunks.append(chunk)

            continue

        # Start a new chunk if adding this block exceeds the target
        if (
            current_blocks
            and current_tokens + block_tokens > MAX_TOKENS
        ):
            chunk = create_chunk(
                parts=current_blocks,
                header_path=header_path,
                source_file=source_file,
                chapter_number=chapter_number
            )

            if chunk:
                chunks.append(chunk)

            current_blocks = []
            current_tokens = 0

        current_blocks.append(block)
        current_tokens += block_tokens

    if current_blocks:
        chunk = create_chunk(
            parts=current_blocks,
            header_path=header_path,
            source_file=source_file,
            chapter_number=chapter_number
        )

        if chunk:
            chunks.append(chunk)


def process_section(
    section: Section,
    parent_headers: list[str],
    chunks: list[Chunk],
    source_file: str,
    chapter_number: str | None
) -> None:
    """
    Processes a section recursively.

    The complete header path is repeated in every chunk.
    """

    current_path = parent_headers + [section.title]

    direct_text = format_direct_content(section)

    if direct_text.strip():
        add_content_to_chunks(
            text=direct_text,
            header_path=current_path,
            chunks=chunks,
            source_file=source_file,
            chapter_number=chapter_number
        )

    for child in section.children:
        process_section(
            section=child,
            parent_headers=current_path,
            chunks=chunks,
            source_file=source_file,
            chapter_number=chapter_number
        )


# ============================================================
# File processing
# ============================================================

def chunk_markdown_file(path: Path) -> list[Chunk]:
    text = path.read_text(
        encoding="utf-8",
        errors="ignore"
    )

    chapters = parse_markdown(text)
    chunks: list[Chunk] = []

    for chapter in chapters:
        chapter_number_match = re.search(
            r"CHAPITRE\s+([0-9]+(?:\.[0-9]+)*)",
            chapter.title,
            re.IGNORECASE
        )

        chapter_number = (
            chapter_number_match.group(1)
            if chapter_number_match
            else None
        )

        process_section(
            section=chapter,
            parent_headers=[],
            chunks=chunks,
            source_file=path.name,
            chapter_number=chapter_number
        )

    return chunks


def process_directory() -> None:
    if not DATA_DIR.exists():
        raise FileNotFoundError(
            f"Directory does not exist: {DATA_DIR}"
        )

    markdown_files = sorted(
        path
        for path in DATA_DIR.glob(PAGE_FILE_PATTERN)
        if path.is_file()
    )

    if not markdown_files:
        print(
            f"No Markdown files matching "
            f"'{PAGE_FILE_PATTERN}' found in {DATA_DIR}"
        )
        return

    all_chunks: list[dict[str, Any]] = []

    global_chunk_id = 0

    for file_path in markdown_files:
        print(f"Processing: {file_path.name}")

        file_chunks = chunk_markdown_file(file_path)

        for chunk in file_chunks:
            all_chunks.append(
                {
                    "chunk_id": global_chunk_id,
                    "text": chunk.text,
                    "token_count": chunk.token_count,
                    "header_path": chunk.header_path,
                    "chapter_number": chunk.chapter_number,
                    "source_file": chunk.source_file
                }
            )

            global_chunk_id += 1

        print(f"  Chunks generated: {len(file_chunks)}")

    with OUTPUT_FILE.open(
        "w",
        encoding="utf-8"
    ) as output_file:
        for chunk in all_chunks:
            output_file.write(
                json.dumps(
                    chunk,
                    ensure_ascii=False
                ) + "\n"
            )

    print()
    print(f"Files processed: {len(markdown_files)}")
    print(f"Total chunks: {len(all_chunks)}")
    print(f"Output: {OUTPUT_FILE}")


def process_document() -> None:
    if not INPUT_FILE.exists():
        raise FileNotFoundError(
            f"Input document does not exist: {INPUT_FILE}"
        )

    print(f"Processing: {INPUT_FILE.name}")

    chunks = chunk_markdown_file(INPUT_FILE)

    with OUTPUT_FILE.open(
        "w",
        encoding="utf-8"
    ) as output_file:

        for chunk_id, chunk in enumerate(chunks):
            record = {
                "chunk_id": chunk_id,
                "text": chunk.text,
                "token_count": chunk.token_count,
                "header_path": chunk.header_path,
                "chapter_number": chunk.chapter_number,
                "source_file": chunk.source_file,
            }

            output_file.write(
                json.dumps(
                    record,
                    ensure_ascii=False
                ) + "\n"
            )

    print()
    print(f"Chunks generated: {len(chunks)}")
    print(f"Output: {OUTPUT_FILE}")

# ============================================================
# Entry point
# ============================================================
if __name__ == "__main__":
    process_document()